export const MODAL_TYPES = {
    CREATE_BOARD: 'CREATE_BOARD',
    INVITE_USER: 'INVITE_USER',
    TASK_DETAIL: 'TASK_DETAIL',
    CREATE_TASK: 'CREATE_TASK',
    CREATE_COLUMN: 'CREATE_COLUMN',
    SEND_INVITATION_MEMBER: 'SEND_INVITATION_MEMBER',
} as const;
